name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Extract changelog
      id: extract_changelog
      run: |
        # Extract the changelog for this version
        changelog=$(sed -n "/## \[${{ steps.get_version.outputs.VERSION }}\]/,/## \[/p" CHANGELOG.md | sed '$ d')
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$changelog" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Changes in this Release
          
          ${{ steps.extract_changelog.outputs.CHANGELOG }}
          
          ## Installation
          
          ```bash
          pip install bojdata==${{ steps.get_version.outputs.VERSION }}
          ```
          
          ## Documentation
          
          See the [README](https://github.com/${{ github.repository }}/blob/main/README.md) for usage instructions.
        draft: false
        prerelease: false